# Generated by Django 6.0.3 on 2026-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
