# Generated by Django 6.0.3 on 2026-04-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_application_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='status',
        ),
    ]
